# Generated by Django 3.1.7 on 2021-02-25 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=32)),
                ('nome_dividendo', models.CharField(max_length=12)),
                ('quantidade_de_x_dividido', models.FloatField()),
                ('valor_mensal', models.FloatField()),
                ('valor_total', models.FloatField()),
                ('categoriasaida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='controle.categoria')),
                ('situacaosaida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='controle.situacao')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=32)),
                ('quantidade_de_x_dividido', models.FloatField()),
                ('valor_mensal', models.FloatField()),
                ('valor_total', models.FloatField()),
                ('categoriaentrada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='controle.categoria')),
                ('situacaoentrada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='controle.situacao')),
            ],
        ),
    ]
